backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "ব্লগ পোস্ট"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "শিরোনাম (Title)", name: "title", widget: "string"}
      - {label: "ফিচারড ইমেজ (Image)", name: "image", widget: "image", required: false}
      - {label: "তারিখ (Publish Date)", name: "date", widget: "datetime"}
      - {label: "সংক্ষিপ্ত বিবরণ (Short Summary)", name: "summary", widget: "text", required: false}
      - {label: "মূল লেখা (Body)", name: "body", widget: "markdown"}
